language: node_js
node_js:
    - "12"
dist: trusty
services:
    - mongodb
    - redis-server
env:
    - NODE_ENV=dev
cache:
    directories:
        - node_modules
install:
    - npm install
    - npm run build
script:
    - nohup npm run start &
    - sleep 3
    - npm run test